## BOF Admin Service Dubbo
#对应ApplicationConfig Dubbo应用配置
dubbo.application.name=hwj-user-center
dubbo.application.owner=com.hwj.user.center
dubbo.application.organization=hwj
dubbo.application.logger=slf4j
dubbo.application.compiler=javassist

#对应ConfigCenterConfig Dubbo内置配置中心
dubbo.config-center.address=nacos://nacos-naming-global-daily-1.hszq8.com:8848?backup=nacos-naming-global-daily-2.hszq8.com:8848,nacos-naming-global-daily-3.hszq8.com:8848&namespace=dubbo-hspt-uat-ksa|nacos://nacos-naming-global-daily-1.hszq8.com:8848?backup=nacos-naming-global-daily-2.hszq8.com:8848,nacos-naming-global-daily-3.hszq8.com:8848&namespace=dubbo-fin-uat-ksa

#对应RegistryConfig Dubbo注册中心
dubbo.registries.registry-hwj.id=registry-hwj
dubbo.registries.registry-hwj.address=nacos://nacos-naming-global-daily-1.hszq8.com:8848?backup=nacos-naming-global-daily-2.hszq8.com:8848,nacos-naming-global-daily-3.hszq8.com:8848&namespace=dubbo-hspt-uat-ksa
dubbo.registries.registry-hwj.group=dubbo-plat
dubbo.registries.registry-hwj.session=60000
dubbo.registries.registry-hwj.register=true
dubbo.registries.registry-hwj.subscribe=true
dubbo.registries.registry-hwj.check=true

#对应ProtocolConfig Dubbo协议配置，服务提供者需配置，消费者不需要
dubbo.protocols.protocol-hwj-user-center-server.id=protocol-hwj-user-center-server
dubbo.protocols.protocol-hwj-user-center-server.name=dubbo
dubbo.protocols.protocol-hwj-user-center-server.dispatcher=message
dubbo.protocols.protocol-hwj-user-center-server.threadpool=limited

#对应ProviderConfig Dubbo服务器提供这配置，本质上是DubboService的公共配置
dubbo.providers.provider-hwj-user-center-server.protocolIds=protocol-hwj-user-center-server
dubbo.providers.provider-hwj-user-center-server.registryIds=registry-hwj
dubbo.providers.provider-hwj-user-center-server.cluster=failover
dubbo.providers.provider-hwj-user-center-server.loadbalance=leastactive
dubbo.providers.provider-hwj-user-center-server.serialization=hessian2
dubbo.providers.provider-hwj-user-center-server.retries=0
dubbo.providers.provider-hwj-user-center-server.timeout=3000
dubbo.providers.provider-hwj-user-center-server.proxy=javassist
dubbo.providers.provider-hwj-user-center-server.delay=-1
dubbo.providers.provider-hwj-user-center-server.group=hwj-user-center-server
dubbo.protocols.protocol-hwj-user-center-server.threads=200
## EOF Admin Service Dubbo

##MySQL
hwj.data-source.druid.driver-class-name=com.mysql.cj.jdbc.Driver
hwj.data-source.druid.url=jdbc:mysql://127.0.0.1:3306/hwj_basic
hwj.data-source.druid.username=root
hwj.data-source.druid.password=root
hwj.data-source.druid.initial-size=5
hwj.data-source.druid.max-active=20
hwj.data-source.druid.min-idle=5
hwj.data-source.druid.max-wait=5000
hwj.data-source.druid.keep-alive=true
hwj.data-source.druid.remover-abandoned=true
hwj.data-source.druid.test-on-borrow=true
hwj.data-source.druid.remover-abandoned-timeout=180

##Mybatis-Plus
#mybatis-plus.configuration.map-underscore-to-camel-case=true
#mybatis-plus.configuration.auto-mapping-behavior=full
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.config-location=classpath:/hwj-basic-server-mybatis/mybatis-configuration.xml
mybatis-plus.type-aliases-package=com.hwj.basic.server.*.entity
mybatis-plus.global-config.db-config.logic-delete-field=deleted
mybatis-plus.global-config.db-config.logic-not-delete-value=0
mybatis-plus.global-config.db-config.logic-delete-value=1






